name: Observability CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Runner Information
        shell: powershell
        run: |
          Write-Host "Runner is working"

          kubectl version --client

          kubectl get nodes

          kubectl get ns

          git --version